#url: https://y7kim.github.io
url: https://maurice1979.github.io

jekyll_analytics:
  GoogleAnalytics:          # Add, if you want to track with Google Analytics
    id: UA-149263600-1      # Required - replace with your tracking id
    anonymizeIp: false      # Optional - Default: false - set to true for anonymized tracking

# Site settings
title: Jordi Vidal de Llobatera's Personal Page
email: is.maurice@pm.me
description: "Jordi Vidal de Llobatera's personal web page."


# Team names, titles and social links
people:
- name: Jordi Vidal de Llobatera
  pic: 1
  position: Data Scientist & Renewable Energy Specialist
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/jordividaldellobatera/
    - title: stack-overflow
      url: https://stackoverflow.com/users/4420297/jordi-vidal-de-llobatera?tab=profile
    - title: github
      url: https://github.com/maurice1979
    - title: git
      url: https://gitlab.com/is.maurice
#    - title: twitter
#      url: https://twitter.com/jordi_vdll


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://www.linkedin.com/in/jordividaldellobatera/
  - title: stack-overflow
    url: https://stackoverflow.com/users/4420297/jordi-vidal-de-llobatera?tab=profile
  - title: github
    url: https://github.com/maurice1979
  - title: git
    url: https://gitlab.com/is.maurice
  # - title: telegram
  #   url: <a href="mailto:is.maurice@pm.me</a>
  # - title: twitter
  #   url: http://twitter.com/jekyllrb

# Postal address (add as many lines as necessary)
address:
  - line: Barcelona
  - line: 08006, Spain

# Build settings
markdown: kramdown
permalink: pretty
theme: jekyll-theme-cayman